# Generated by Django 2.2.1 on 2019-05-29 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TasPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_ident', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Unpaid'), (2, 'Pending'), (3, 'Running'), (4, 'Completed')])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='auto.Entity')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='auto.TasPackage')),
            ],
        ),
    ]
