# Generated by Django 2.2.1 on 2019-05-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TasPackage',
            new_name='TaskPackage',
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Task Entity', 'verbose_name_plural': 'Task Entities'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskpackage',
            options={'verbose_name_plural': 'Task Packages'},
        ),
    ]
