# Generated by Django 2.2.1 on 2019-07-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_20190529_0910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entity',
            new_name='Action',
        ),
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Task Action', 'verbose_name_plural': 'Task Actions'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='entity_type',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='taskpackage',
            old_name='entity_type',
            new_name='action',
        ),
        migrations.AddField(
            model_name='task',
            name='address',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='random_token',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unpaid'), (2, 'Pending'), (3, 'Running'), (4, 'Completed')], default=2),
        ),
    ]
