# Generated by Django 2.2.1 on 2019-07-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_auto_20190723_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='initial_member',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
