# Generated by Django 2.2.1 on 2019-07-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_task_initial_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='entity_ident',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
