# Generated by Django 2.2.1 on 2019-07-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_auto_20190724_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='entity_ident',
            field=models.CharField(max_length=200, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('entity_ident', 'status')},
        ),
    ]
