# Generated by Django 2.2.1 on 2019-07-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_auto_20190724_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='initial_member',
            new_name='member_count',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
