# Generated by Django 2.2.1 on 2019-07-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_runningtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runningtask',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='runningtask',
            name='identifier',
        ),
        migrations.AddField(
            model_name='runningtask',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='running_tasks', to='auto.Task'),
            preserve_default=False,
        ),
    ]
