# Generated by Django 2.2.1 on 2019-07-26 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0014_invoice_expected_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='auto.Invoice'),
        ),
    ]
