# Generated by Django 2.2.1 on 2019-07-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0015_auto_20190726_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
    ]
